### ISSUE TITLE
Can't use decorators in class methods

### ISSUE THREAD

**Issue by Kunoacc** [jeffijoe/awilix-koa#13]
When I try to follow the code snippet in the README and use decorators in my router classes and methods when I add the decorators to my methods, the server fails to run and returns 'The "verbs" decorator can only be used on class verbs'

js```
 import bodyparser from "koa-bodyparser";
import { route, GET, POST, before } from "awilix-koa";

@route('/places')
export default class Places{
    constructor({PlacesService}){
        this.service = PlacesService;
    }

    @route('/list')
    @GET()
    async listPlaces(ctx){
        

    }
}
```

**Comment by jeffijoe** [comment]
What decorator style are you using? Legacy or the newer one? The decorators only work with `legacy-decorators` (Babel) and `experimentalDecorators` (TypeScript)

**Comment by Kunoacc** [comment]
I opened the issue in babel and they said to switch to legacy
It's working now.
Thanks
