### ISSUE TITLE
[Help] Using Inject

### ISSUE THREAD

**Issue by brianupskill** [jeffijoe/awilix-koa#14]
Hi Jeff, thank you so much for all the support and I absolutely love Awilix. 

I am trying to `inject` a middleware into my koa router as follows:
```
const Router = require('koa-router')
const { inject } = require('awilix-koa')

const DevicesController = {
  get router() {
    const router = new Router()

    router.use(inject('deviceSerializer'))

    router.post('/', inject('createDevice'), this.create)

    return router
  },
 // ... my create function here....
```
 and I'm getting an error 
`build: expected targetOrResolver to be a function or class, but got deviceSerializer.`
which is self-explanatory...
I register my serializer in container.js as follows...
```
// Serializers
container.register({
  deviceSerializer: asValue(DeviceSerializer)
})
```
but it seems that it can't resolve the serializer.

I am following [this repo](https://github.com/talyssonoc/node-api-boilerplate) but as I like their folder structure and architecture but would love to plug in Koa instead of Express.  

I would appreciate all help and any guidance.

**Comment by jeffijoe** [comment]
The repo you linked is for Express and is using an old version of the bindings, inject takes a function that gets called with dependencies.

**Comment by jeffijoe** [comment]
See https://github.com/jeffijoe/koa-es7-boilerplate for reference 😄
