### ISSUE TITLE
[Question] Regarding the koa-router new maintainer

### ISSUE THREAD

**Issue by guillaumemaka** [jeffijoe/awilix-koa#16]
Hi @jeffijoe , 

I would like to know what's your plan regarding the koa-router package being sold to a new maintainer and the one forked by the koajs organization.

Will you still use the same library or use the @koa/koa-router fork?

Regards.

**Comment by jeffijoe** [comment]
I'll move to `@koa/router`, but there are no type definitions for it.

**Comment by jeffijoe** [comment]
Updated and released as v4. Thanks!
