### ISSUE TITLE
Question on load controllers

### ISSUE THREAD

**Issue by jhasselgren** [jeffijoe/awilix-koa#22]
Hi,
Is it possible to load a controller like this:
```
import { createController, controller } from 'awilix-koa';
export const previewController = () => {
  return controller(
    createController(makePreviewApi)
      .prefix('/preview')
      .get('/:id', 'getPreview'),
  );
};
```

Or is it only possible with loadControllers? 

(The problem I have is that the route never gets added)

**Comment by jeffijoe** [comment]
Yeah that should work just fine. Each `controller()` creates its' own router. See [the tests](https://github.com/jeffijoe/awilix-koa/blob/3a8eeb952c5eb6cc7d3a1e58739b9815b5080271/src/__tests__/controller.test.ts#L67).

**Comment by jhasselgren** [comment]
ok, found was the problem was, I cannot add a controller to a Router, but when I add it to the koa app then it works.

const apiRouter = new Router();
apiRouter.use(previewController()); => Does not work

const koa = new Koa();
koa.use(previewController()); => works
