### ISSUE TITLE
can't use inject or injector inside container.register on controller

### ISSUE THREAD

**Issue by felipeOliveira** [jeffijoe/awilix-koa#24]
I`m created a function that receive 3 arguments, where one of these arguments i create using injector because I use a name of function/controller as reference. e.g: 

```javascript 
makeMyController({repository, serviceA, logger}) {...}
````
and my container: 
```javascript
container.register({
    repository: asFunction(makeRepository,{injector:()=>({logger: Logger('MyRepo')})),
    serviceA: asFunction(makeServiceA,{injector:()=>({logger: Logger('MyServiceA')})),
   controller: asFunction(makeController,{injector:()=>({logger: Logger('MyController')}))
})
```

when I run koa, and call the endpoint, the api returns 404 and on console print the following message: `error while process /leads. Could not resolve 'logger'` <<< this is formated message from my errorhandler.

But if I remove logger parameter from makeMyController function, this run normally, and others dependencies receive your own logger instance.

**Comment by jeffijoe** [comment]
That's odd, could you try changing it to the fluent syntax?

```js
asFunction(makeRepository).inject(()=>({ logger: Logger('MyRepo') }))
```

**Comment by felipeOliveira** [comment]
The same result.

```javascript
import { createController } from 'awilix-koa';
import makeLeadController from '../core/leads/controller';

export default createController(makeLeadController) //this is the only class/func that not receive a logger
  .get('/leads', 'listLeads')
```

all dependencies chain that have a logger as dependency is created normally

**Comment by jeffijoe** [comment]
Oh, that's because `awilix-koa` does not resolve the `controllers` that way. It will take whatever you pass to `createController` and build a plain resolver, then build it up. If you really want to register your controllers too, there's no point in using `awilix-koa`s controllers, just use `inject` and `koa-router`.

If you really want to do this, you can do `createController(({ controller }) => controller)`

Alternatively, have a middleware in Koa before your controllers register a logger (I recommend doing this):

```ts
app.use((ctx, next) => {
  ctx.state.container.register('logger', Logger('http', {
    // assuming you can add extra context to your logs
    method: ctx.request.method,
    url: ctx.request.url
  }))
  return next()
})
```

**Comment by felipeOliveira** [comment]
um ... I understood, but it would be interesting in the future to allow the use of inject in controllers, because for example, in the current way I cannot create a specific logger for the controller, I would not be able to know which controller I am creating the logger in a middleware before, because there is no way to access which controller will be created for me to create the logger with the specific name
