### ISSUE TITLE
Trying to access route params in app level middleware

### ISSUE THREAD

**Issue by oldmanfleming** [jeffijoe/awilix-koa#25]
I'm not sure if this is intended but using the decorator example provided in the docs I would simply like to have access to route params in my middleware attached to the app.

It seems I can access the params if I declare the middleware in the before of the controller itself but I would like to potentially have access to route params of each request in a global middleware on the app itself. Is this possible?

**server.js**
```import * as Koa from "koa";
import { createContainer } from "awilix";
import { loadControllers, scopePerRequest } from "awilix-koa";

const app = new Koa();
const container = createContainer();
app.use(scopePerRequest(container));
app.use((ctx, next) => {
  console.log(ctx.params);
  return next();
}); // undefined
app.use(loadControllers("routes/*.js", { cwd: __dirname }));

app.listen(3000);
```

**users-api.js**
```
import { route, GET } from "awilix-koa"; // or `awilix-router-core`

@route("/users")
export default class UserAPI {
  constructor() {}

  @route("/:id")
  @GET()
  async getUser(ctx) {
    ctx.body = ctx.params.id;
  }
}
```

Is there an intended way of doing this?

**Comment by jeffijoe** [comment]
Use `loadControllers` before you try to access the route params.

EDIT: Sorry just read that again. No you would have to register that middleware as `before` on each controller.

**Comment by oldmanfleming** [comment]
Okay, sounds like this is intended behavior. My desire was that I have certain middleware I need to write that will essentially have to be added to every controller no matter what and it needs to access the route params. It would be great to added it once on the app but it sounds like this is not intended so I will have to settle for adding it on each controller individually. Thanks for the quick response!
