### ISSUE TITLE
it occur 501 error, when after is used with await next()

### ISSUE THREAD

**Issue by chocholand** [jeffijoe/awilix-koa#5]
//api
```
@POST()
@after([generate()])
  async create(ctx, next) {
    ...
    next()
  }
```

//middleware
```
function generateToken() {
  return async(ctx, next) => {
    const { data } = ctx.state
      ...
      await next()      => if it remove, working
     ...
      ctx.ok(data)
    }
  }
}
```

**Comment by jeffijoe** [comment]
You need to `await next()` in the first one. :)

**Comment by chocholand** [comment]
I did. But it still 501 error.

**Comment by jeffijoe** [comment]
Awilix Koa does not set a 501 status anywhere so it must be somewhere else.

Despite that, I’d like to help you out if you can provide a reproduction repository. 😀

**Comment by chocholand** [comment]
I found it.
I use this with next.js
so I had to add this at end middleware
```
  .use(async(ctx) => {
    await handle(ctx.req, ctx.res)
    ctx.respond = false
  })
```

in awilix-koa v1
I can do like this.
```
  router.get('*', async ctx => {
    await handle(ctx.req, ctx.res)
    ctx.respond = false
  })
```

but in awilix-koa v2
I can't get Router instance. so I made the expedient method.

**Comment by jeffijoe** [comment]
The approach you used for v2 is better either way, as you didnt need to use the router to add that middleware. 😀

What exactly is Next doing thats causing this?

**Comment by chocholand** [comment]
next.js that is server-side rendering framework must to have handle function at last middleware.

handle function make page.

'localhost:5000/api/user' ===> call user-api
'localhost:5000/mypage' ===> server rendering page

v2
```
    .use(loadControllers('../routes/**/*-api.js', { cwd: __dirname }))
    .use(async(ctx) => {
      await handle(ctx.req, ctx.res)
      ctx.respond = false
  })
```

v1
```
  createApis(router)

  router.get('*', async ctx => {
    await handle(ctx.req, ctx.res)
    ctx.respond = false
  })
```

**Comment by jeffijoe** [comment]
Glad you figured it out!
