### ISSUE TITLE
"Globbing" Controllers w/ Webpack

### ISSUE THREAD

**Issue by jdscolam** [jeffijoe/awilix-koa#56]
I'm in a situation where I want to glob all my controllers together automatically as demonstrated, but I'm using Webpack to reduce the file-sizes and directory complexity.  Do you have any suggestions with how to approach that?  I have a separate routes folder as in your example, but I'm not sure that would work properly when minified.

**Comment by jeffijoe** [comment]
You would have to write your own webpack-compatible glob loader.

Why use webpack on the server though?

**Comment by jdscolam** [comment]
Great question, basically minification and built-in transpilation all at once.  Makes for an easy way to adopt modern JS without relying on TypeScript.

**Comment by jeffijoe** [comment]
Interesting. Why minify when running on the server? Why do you feel you can’t adopt modern JS without TS?

**Comment by jdscolam** [comment]
Honestly, the minification is to reduce the size of deployments for speed/cost issues.  Also I'm trying to avoid TS at all costs, so Webpack is killing two birds with one stone there.

BTW:  Can I pass an array of simple decorated classes (e.g. [MyController, MyController2, ...]) to the controller function?

**Comment by jeffijoe** [comment]
Yes you can.
