### ISSUE TITLE
how to get Router instance.

### ISSUE THREAD

**Issue by chocholand** [jeffijoe/awilix-koa#6]
similar to #5 
I think router instance is will more often used.
SSR, acl([koa-2-acl](https://github.com/JefferyLiang/koa-2-acl))

how about awilix-koa give it back?

**Comment by jeffijoe** [comment]
Why do you need access to the router for that? You can use `app.use()` which is the same as `router.use()`.

**Comment by jeffijoe** [comment]
Also, if you really _really_ need access to a router specifically, why not wrap it?

```js
const router = new Router()
router.use(loadControllers('./api/*.js'))
router.use(...)

app.use(router.routes())
```

`awilix-koa`'s `loadController` and `controller` use Koa Router under the hood to configure routes declaratively, but in the end it's just middleware, which you can compose however you like.

If you want full control, you can use `makeInvoker` and set up routes yourself. 😄

**Comment by chocholand** [comment]
Gooood!!
I didn't think about that.
Thank you very much.

**Comment by brianupskill** [comment]
I would like to give my support for this feature. I tried to wrap the `loadControllers` function in a koa-router and passing that router to the koa app instance with the above example. Unfortunately, the endpoints weren't hit. Additionally, I would like to further configure the router upon which my controller will be loaded with something like this: 
```
app.use(router.routes());
app.use(router.allowedMethods({
  throw: true,
  notImplemented: () => new Boom.notImplemented(),
  methodNotAllowed: () => new Boom.methodNotAllowed()
}));
```
How could that be achieved?

**Comment by jeffijoe** [comment]
Koa Router is an implementation detail, so I would rather not expose it, but I could allow passing in your  own router, just seems... weird.

**Comment by gotrecillo** [comment]
would be nice to have it. so we can do something like this https://github.com/chuyik/koa-joi-router-docs

**Comment by jeffijoe** [comment]
@gotrecillo that still wouldn't be possible even if we switched internally because there's no extension point to put the validation rules. I would suggest you use `inject()`, then you can use whatever router you want.
