### ISSUE TITLE
Lack of router control

### ISSUE THREAD

**Issue by dlgoodchild** [jeffijoe/awilix-koa#61]
Hi, is there any chance that `loadControllers` could either just return the `Router` instance instead of a `compose`'d middleware, or accept an optional `Router` as an argument (this would be more backwards compatible).
Either of these approaches would give some kind of control over the router. Without it, we can do nothing.

I tried to use the return value with my own `Router`, but it seems that the `compose` middleware is incompatible, and therefore can only be applied directly to your `app` (`Koa`) instance. I'm finding this is hindering me a lot for the level of configuration I'd like. I'm happy to open a PR for this, but I want to check first that you'd be open to this change?

**Comment by jeffijoe** [comment]
Allowing to pass in an optional `router` to `controller` and `loadControllers` is probably the most backwards-compatible.

At the time, the Koa Router package did not have types, so a `const router = require('@koa/router')` is needed, and caused me to not accept it as a parameter due to necessitating `any`. If this is now possible, then I am happy to accept a PR for this.

**Comment by dlgoodchild** [comment]
I have been working with a locally modified version of the build to first trial some changes before making a PR.
I think passing an optional `Router` is definitely a useful addition, however I would actually like to propose that I add a `makeControllers` method, ass per:

```
export function makeControllers(router: Router, pattern: string, opts?: IOptions): void {
  findControllers(pattern, {
    ...opts,
    absolute: true,
  }).forEach(_registerController.bind(null, router))
}
```

We can then update `loadControllers` to become:
```
export function loadControllers(pattern: string, opts?: IOptions, router?: Router): Middleware {
  const r = router || new Router()
  makeControllers(r, pattern, opts)
  return compose([r.routes(), r.allowedMethods()]) as any
}
```

In `loadControllers` it gives the user an option to modify the router before being used as middleware on Koa directly.
The `makeControllers`, requires a `Router`, hence it being the first arg, and has no return type as it's acting directly on an object.

This is backwards compatible, adds flexibility and introduces leveraging everything loadControllers was building but without enforcing a particular usage.

What are your thoughts?

**Comment by jeffijoe** [comment]
I think the signature makes sense, but the name `makeControllers` does not make it immediately obvious that we are loading the controllers as well.

Even though `loadControllers` returns composed middleware, AFAIK calling `.routes()` on the router does not have any side effect, so technically it would be no different if you just ignore the return value, right?

**Comment by dlgoodchild** [comment]
I've opened a PR...happy to take on any feedback.

**Comment by dlgoodchild** [comment]
I've just created a new PR, it was easier. Updated the API sections of README as requested.
