### ISSUE TITLE
First, npm run dev

### ISSUE THREAD

**Issue by Leekyungun** [jeffijoe/awilix-koa#7]
I use router awilix-koa. and run.

api file : /src/routes/user/user-api.js
error  : @route()

==========================

It turned out to be an error caused by not switching to Babel. 
I added the file below. (.babelrc)

**Comment by Leekyungun** [comment]
I added this file. (.babelrc )
The next error came out.
![image](https://user-images.githubusercontent.com/12290390/41953344-0dcc8ac2-7a10-11e8-96f6-6d26b08b1beb.png)

**Comment by jeffijoe** [comment]
Glad you got it fixed, but how did you get that “Could not resolve {“ error?

**Comment by Leekyungun** [comment]
I didn't get  that “Could not resolve {“ error.
But I found out where it happened.
![image](https://user-images.githubusercontent.com/12290390/41958948-90434674-7a26-11e8-9be5-1686105c3c3f.png)
That part works well if you delete it.(resolutionMode: ResolutionMode.CLASSIC)
I don't know What does it do?
I think you're really great.

Can I use that part after deleting it?

**Comment by jeffijoe** [comment]
Oh, I see! You were using `CLASSIC` injection but your modules were written using destructuring syntax which is for `PROXY` (default).

You can use whatever you wish. :)

**Comment by jeffijoe** [comment]
Also, your Awilix is outdated it seems, in `v3` it is called `InjectionMode`. 😄

Edit: I see you're using my boilerplate, awesome! I'm going to update it now so it runs on the latest versions. :)

**Comment by Leekyungun** [comment]
Thank you~!
I want to contribute after I gain my skills.
Have a nice day~

**Comment by jeffijoe** [comment]
You're welcome! I just pushed an update to the boilerplate. 😄
