### ISSUE TITLE
Lifetime question

### ISSUE THREAD

**Issue by Leekyungun** [jeffijoe/awilix-koa#8]
Hi, me again.

I make middleware that save token in container.
![image](https://user-images.githubusercontent.com/12290390/42014917-dd257c50-7adf-11e8-93ff-f889f20bd0f3.png)

And use like this.
![image](https://user-images.githubusercontent.com/12290390/42014946-f8c45c74-7adf-11e8-8330-3f6940d43f83.png)

then, error message is 
![image](https://user-images.githubusercontent.com/12290390/42014959-0871c33c-7ae0-11e8-90b9-bee6f4de9c47.png)

I don't know lifetime setting. 
![image](https://user-images.githubusercontent.com/12290390/42014993-2387badc-7ae0-11e8-932e-9c1ab3289ca5.png)

Help~

**Comment by jeffijoe** [comment]
You need to use the `asValue` resolver when registering the token. 😀

```js
import { asValue } from 'awilix'

container.register({
  token: asValue(token)
})
```

**Comment by Leekyungun** [comment]
Oh! Thank you!!! 
I thought the container related setup file was strange.

Really Thank you!!!!
