### ISSUE TITLE
To upload a file to a board

### ISSUE THREAD

**Issue by Leekyungun** [jeffijoe/awilix-koa#9]
Hi :  ) 
I want to board that can upload file.

![image](https://user-images.githubusercontent.com/12290390/44459264-fb10c500-a643-11e8-8c7a-fa70857fa569.png)

this source can upload text. 
but i don't know How can I upload file. 

It seems like using a multer module. I don't know how to apply it to Koa.

Can you help me? T . T

**Comment by jeffijoe** [comment]
That is not an `awilix-koa` related question, but I'll try to help anyway.

This depends on how you want to process your file. If you just want it as plain text without saving it to a file first, or if you want to stream it somewhere, you can use Busboy.

Check out [this Gist](https://gist.github.com/jeffijoe/60c7a1fbf36a767477c82b9fe651fe48) with an example.

**Comment by Leekyungun** [comment]
Thank you ~ !
I didn't know that Multer was from busboy.
I modified the busboy.js file to receive multiple files.

```
import Busboy from 'busboy'
import fs from 'fs'

/**
 * Parses a single file from a Node request.
 *
 * @param  {http.IncommingRequest} req
 * @return {Promise<{ file: Stream, filename: string>}
 */
export default function parse (req) {
  return new Promise((resolve, reject) => {
    const returnObject = {}
    returnObject.filename = []

    const busboy = new Busboy({
      headers: req.headers,
      limits: {
        fileSize : 1 * 1024 * 1024  //파일사이즈 byte 단위
        //files: 1 //파일 갯수
      }
    })

    busboy.on('file', _onFile)
    busboy.on('field', _onField)
    busboy.once('error', _onError)
    busboy.once('finish',_onFinish)

    req.pipe(busboy)
   
    function _onFile (fieldname, file, filename) {
      if(file)
        file.pipe(fs.createWriteStream(`.\\uploads\\${filename}`))
      
      returnObject.filename.push(filename)
    }

    function _onField (fieldname, val) {
      returnObject[fieldname] = val
    }

    function _cleanup () {
      busboy.removeListener('file', _onFile)
      busboy.removeListener('field', _onField)
      busboy.removeListener('error', _onError)
      busboy.removeListener('finish', _onFinish)
    }

    function _onFinish () {
      _cleanup()
      resolve( returnObject )
    }

    function _onError (err) {
      _cleanup()
      reject(err)
    }
  })
}
```

I want you to see what it's like.
Really Thank you ~ !
